apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 60s }
        - setWeight: 100
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/rmprog/ci_cd_lab@sha256:26bad0efee7c57a5e2a25baf5246a47e07791a61573125c0aae05de5fb8369a6
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
